CREATE DATABASE KALBE3;
USE KALBE3;

CREATE TABLE karyawan (
	id INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    AGE INT,
    SEX VARCHAR(6),
    INCOME DECIMAL(10, 2)
);